id = "org.standardnotes.standard-sheets"
npm = "sn-spreadsheets"
github = "sn-extensions/secure-spreadsheets"
main = "dist/index.html"

name = "Secure Spreadsheets"
content_type = "SN|Component"
area = "editor-editor"
version = "1.3.3"
marketing_url = "https://s3.amazonaws.com/standard-notes/screenshots/models/editors/spreadsheets.png"
thumbnail_url = ""
description = "A powerful spreadsheet editor with formatting and formula support. Not recommended for large data sets, as encryption of such data may decrease editor performance."
flags = []
